apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  {{- if .Values.backend.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.serviceAccount.roleArn }}
  {{- end }}
